name: Promote app to production

on:
  # We will remove this later, but it's required to get the workflow to show up initially
  push:
    branches: [ 3-configure ]

  workflow_dispatch:

jobs:
  promote:

    runs-on: ubuntu-latest

    steps:
      - name: Install Heroku
        run: |
          curl https://cli-assets.heroku.com/install-ubuntu.sh | sh

      - name: Heroku promote app
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku pipelines:promote -a casey-devops-stg
